Prefix secrets names with release name
so that each release can have their own secrets, i.e.
we can deploy packit-production-validation & packit-staging-validation
into one namespace. Otherwise Helm fails with
Error: rendered manifests contain a resource that already exists.

Hardcode values not expected to be changed (like container name)
to symplify things.